name = "remix"
roles = ["frontend", "backend"]
webhooks_path = "/webhooks/app/uninstalled"

[commands]
predev = "echo 'Starting with Drizzle + local D1 database'"
dev = "wrangler dev --config wrangler.jsonc --local"
