#:schema node_modules/wrangler/config-schema.json
name = "shopify-cloudflare-app"
main = "build/server/index.js"
compatibility_date = "2025-01-14"
compatibility_flags = ["nodejs_compat"]

# Environment variables for development/staging
[vars]
SHOPIFY_API_KEY = "your-api-key"
SHOPIFY_APP_URL = "https://your-app.pages.dev"
SCOPES = "write_products"

# D1 Database bindings
# To create a D1 database, run: wrangler d1 create shopify-app
# Then update the database_id below
# [[d1_databases]]
# binding = "DB"
# database_name = "shopify-app"
# database_id = "your-database-id"

# Static assets (for Pages deployment)
[site]
bucket = "./build/client"

# Preview/Development environment
[env.preview]
name = "shopify-cloudflare-app-preview"

# Production environment
[env.production]
name = "shopify-cloudflare-app-production"
vars = { SHOPIFY_APP_URL = "https://your-production-app.pages.dev" }

# Build configuration
[build]
command = "bun run build:cloudflare"